/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Juliana
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnaula = new javax.swing.JButton();
        btnmateria = new javax.swing.JButton();
        btnnota = new javax.swing.JButton();
        btnrecuperacao = new javax.swing.JButton();
        btnprofessor = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("ÁREA DO PROFESSOR");

        btnaula.setBackground(new java.awt.Color(255, 153, 0));
        btnaula.setText("AULA");
        btnaula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaulaActionPerformed(evt);
            }
        });

        btnmateria.setBackground(new java.awt.Color(255, 153, 0));
        btnmateria.setText("MATÉRIA");
        btnmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmateriaActionPerformed(evt);
            }
        });

        btnnota.setBackground(new java.awt.Color(255, 153, 0));
        btnnota.setText("NOTA");
        btnnota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotaActionPerformed(evt);
            }
        });

        btnrecuperacao.setBackground(new java.awt.Color(255, 153, 0));
        btnrecuperacao.setText("RECUPERAÇÃO");
        btnrecuperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecuperacaoActionPerformed(evt);
            }
        });

        btnprofessor.setBackground(new java.awt.Color(255, 153, 0));
        btnprofessor.setText("PROFESSOR");
        btnprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofessorActionPerformed(evt);
            }
        });

        btnvoltar.setText("VOLTAR");
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnmateria, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaula, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnota, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrecuperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprofessor, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvoltar))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addComponent(btnvoltar))
                .addGap(18, 18, 18)
                .addComponent(btnaula)
                .addGap(18, 18, 18)
                .addComponent(btnmateria)
                .addGap(18, 18, 18)
                .addComponent(btnnota)
                .addGap(18, 18, 18)
                .addComponent(btnrecuperacao)
                .addGap(18, 18, 18)
                .addComponent(btnprofessor)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaulaActionPerformed
         TelaAula alu = new TelaAula();
         //Mostrando o form quando clicar no botão
         alu.setVisible(true);
    }//GEN-LAST:event_btnaulaActionPerformed

    private void btnmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmateriaActionPerformed
       TelaMateria alu = new TelaMateria();
         //Mostrando o form quando clicar no botão
         alu.setVisible(true);
    }//GEN-LAST:event_btnmateriaActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        TelaInicial ini = new TelaInicial();
        ini.setVisible(true);
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotaActionPerformed
       TelaNota ini = new TelaNota();
        ini.setVisible(true);
    }//GEN-LAST:event_btnnotaActionPerformed

    private void btnrecuperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecuperacaoActionPerformed
       TelaRecuperacao ini = new TelaRecuperacao();
        ini.setVisible(true);
    }//GEN-LAST:event_btnrecuperacaoActionPerformed

    private void btnprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofessorActionPerformed
       TelaProfessor ini = new TelaProfessor();
        ini.setVisible(true);
    }//GEN-LAST:event_btnprofessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaula;
    private javax.swing.JButton btnmateria;
    private javax.swing.JButton btnnota;
    private javax.swing.JButton btnprofessor;
    private javax.swing.JButton btnrecuperacao;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
